### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/snjs#166]
Lately, I've noticed that the sort order of special characters have changed somethat in Standard Notes. For example, - (dash) is sorted beferore ! (exclamation mark) on views in the Android app but not on Standard Notes desktop. Also, the sort order of notes has changed. & (amperstand) is sorted before # (hastag) when it recently was the other way around.

So now I hava a feature request: Keep the same sort order (preferably the standard ASCII sort order - see [link](http://support.ecisolutions.com/doc-ddms/help/reportsmenu/ascii_sort_order_chart.htm)) for views and tags on all platforms (Android, desktop, and web). Also, once a sort order is established, don't change it from one update to another. Some of use use letters and special characters to organize our notes, like in a bullet journal, and would much appreciate if any changes to the sort order is avoided as much as possible.

**Comment by mobitar** [comment]
@baptiste-grob was recently making changes here. I'll have him look into this once he's back next week.

**Comment by baptiste-grob** [comment]
This is the commit in question: https://github.com/standardnotes/snjs/commit/01ca2443a8cd4d3686035365e5c2fa48ffca4f71
The way we used to sort had a bug and was generally not very robust when dealing with anything outside of ASCII characters. We now use localeCompare() which will sort your notes differently depending on the language of your operating system, but is guaranteed to be correct in that language.
Is the sorting discrepancy specific to views? Maybe the desktop or mobile app is doing its own sorting after the fact. (cc @radko93)

**Comment by onlinemumie** [comment]
The sorting discrepancy is not specific to views. It's the same with tags.

**Comment by onlinemumie** [comment]
The web app sorts _ (underscore) differently on two instances of Brave browser, both set to the same language (swedish) and both on computers with linux OS, one on Linux Mint (swedish) and the other on Ubuntu (swedish). Any good links to how the sort order might go for localeCompare() in different languages? For a regular user like me (not a computer engineer, developer, or hacker), it's not very predictable.
