### ISSUE TITLE
Can API version be in header too?

### ISSUE THREAD

**Issue by mdouchement** [standardnotes/snjs#190]
Hello, I want to know if it's possible to add the api version (eg. `20200115`) in the HTTP header too?

My main motivation is that I develop an alternative server that aims to be lightweight and portable and getting the API version from the request's body is not handy.
As my server is developed in a typed language, the JSON is parsed at the end of the HTTP stack in the controllers' handlers. So I can't have the API version in the middlewares level to apply special logic like revoke JWT tokens if the client supports sessions.

**Comment by mobitar** [comment]
Any thoughts on this @karolsojko? Was this an issue for you in syncing-server-js?

**Comment by karolsojko** [comment]
I don't see a problem in having the API version either in request's body or in a header. Maybe it even makes more sense to have this in a custom `X-...` header - depends on what we agree to be consistent across all clients. Would like to avoid a situation where the server has to interpret either body OR header - could cause potential bugs in future, so it's best if we have this consistent and sent in one place (for example header). 

Having that said, providing this change would cause us to do a little bit of a synchronized dance with all the clients and server where we would have to have a state where we interpret both for some period (mobile clients are not updated on the fly). So it's a hard change to pull off at the moment, given the amount of backlog we have. 

Nevertheless I'm all for this idea - just a matter of priority. 

Side topic: @mdouchement we are currently in the process of rewriting our server into TypeScript, maybe something you would be interested in: https://github.com/standardnotes/syncing-server-js
