### ISSUE TITLE
Server history support

### ISSUE THREAD

**Issue by mobitar** [standardnotes/snjs#38]
Consumes this API: https://github.com/standardnotes/syncing-server/pull/60

Session history and Server history should be combined into a single HistoryService interface. Clients should implement a single History menu that separates into two sections: Server History, and Session History. Selecting a revision from either section should present the same UI.

cc @radko93 @baptiste-grob @johnny243

**Comment by johnny243** [comment]
@mobitar when you say Session history, are you referring to [user sessions](https://github.com/standardnotes/syncing-server/blob/develop/app/controllers/api/sessions_controller.rb)?

**Comment by mobitar** [comment]
No, this session history:

<img width="391" alt="Screen Shot 2020-07-08 at 8 42 58 AM" src="https://user-images.githubusercontent.com/3277844/86925912-0d406300-c0f7-11ea-8578-2d85a22b9a17.png">
