### ISSUE TITLE
Test suite, CI

### ISSUE THREAD

**Issue by rafaelespinoza** [standardnotes/snjs#5]
It would be really useful if this library's test suite was available for continuous integration environments, but it seems that the browser dependency makes this difficult. In particular, it would be a great tool for testing a StandardNotes backend implementation.

#### the problem

At the moment, it seems that the test suite can only be run by:

- running `node ./test-server.js`
- open a browser tab to `localhost:9001`

The dependence on a browser makes it difficult to use in continuous integration.

#### some affected projects

There are a few server-side implementations, in addition to the official [syncing-server](https://github.com/standardnotes/syncing-server) such as:

- [dstar4138/standardfile](https://github.com/dstar4138/standardfile)
- [mdouchement/standardfile](https://github.com/mdouchement/standardfile)
- [rafaelespinoza/standardnotes](https://github.com/rafaelespinoza/standardnotes)
- [sealas/elixir-standardfile-server](https://github.com/sealas/elixir-standardfile-server)
- [tectiv3/standardfile](https://github.com/tectiv3/standardfile)

Some of these have test suites, but does it even matter if the client does not work?

#### ideas for solution

Could the test suite be set up to use node? If the execution environment shifted to node, then it would be easier to run the test suite along the side of any of the aforementioned syncing servers.
A docker image and one location to set a server URL in the test would also be really nice to have.

**Comment by mobitar** [comment]
We need a browser because we use WebCrypto in our clients to perform crypto operations. SNJS is dependent on sn-crypto, which includes the WebCrypto code. You can potentially swap this out for Node-based crypto by subclassing, but this might require some work to support.

**Comment by rafaelespinoza** [comment]
I see that sncrypto is on [npm](https://www.npmjs.com/package/sncrypto), but is there a repo anywhere?

**Comment by mobitar** [comment]
Yup: https://github.com/standardnotes/sncrypto

**Comment by karolsojko** [comment]
Hi @rafaelespinoza,

we have a test suite running on CI now (ref: https://github.com/standardnotes/snjs/pull/158)

hope this helps to close this issue :) ?

**Comment by karolsojko** [comment]
Closing the issue. If you feel it needs reopening, please don't hesitate to do so.
