### ISSUE TITLE
make DEFAULT_SYNC_SERVER first party too.

### ISSUE THREAD

**Issue by jackyzy823** [standardnotes/snjs#582]
While self hosting both `web` and  sync server , i want treat sync server (DEFAULT_SYNC_SERVER) defined in `web`'s `.env` as first party   in isUrlFirstParty https://github.com/standardnotes/snjs/blob/1350866a021201795c2aef10c2276ca7be42267f/packages/snjs/lib/hosts.ts#L20-L27 and/or extend `TRUSTED_FEATURE_HOSTS` and `APPLICATION_DEFAULT_HOSTS` list.

**Comment by moughxyz** [comment]
Fixed by https://github.com/standardnotes/snjs/commit/326c05aa71fd4dfd5ca6789f2f8edff15121fd7d
