### ISSUE TITLE
Consider using AEAD encryption like AES-GCM in version 004

### ISSUE THREAD

**Issue by mdouchement** [standardnotes/snjs#71]
In the current implementation, all the user data are encrypted with AES-CBC that is vulnerable to the Padding Oracle attack.

We could use AES-GCM known as more secure than AES-CBC by providing authenticated encryption (AEAD).
ChaCha20-Poly1305 could be a great alternative especially when the device does not support the AES instruction set (that can be the case for smartphones).

**Comment by mobitar** [comment]
Version 004 of the protocol uses XChaCha20-Poly1305 👍 This will be available in the 3.5 client release, which is presently in development.

**Comment by JaspalSuri** [comment]
All new accounts will use the new encryption specification. A rollout of an option to upgrade one's account to the new spec will be available in the future, once the dev team has ironed out some quirks and has stabilized the apps. To upgrade your account today, you can reset your password (optionally with the same password) via the desktop or [web](app.standardnotes.org) apps.
